language: c++
compiler: gcc

before_install:
  - uname -a
  - lsb_release -a
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test     # gcc 4.8
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots       # libsdl2
  - sudo add-apt-repository --yes ppa:kubuntu-ppa/backports       # cmake >=2.8.10
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake


before_script:
   - mkdir build
   - cd build
   - cmake ..

script: 
   - make
